/**
 * Team CODE TITANS - SIH26051
 * Problem Statement: Software Based Model Development for Design of Area-Specific Shelter for Thermal Comfort Maintenance
 * 
 * ReportView.tsx - Printable A4 Engineering Dossier & PDF Generator
 * 
 * Key Features:
 * - Native window.print() trigger for instant browser printing / Save as PDF
 * - Complete Tailwind CSS print: modifiers optimized for A4 paper geometry
 * - Automatic suppression of all web controls, navigation, sliders, buttons, and hover states
 * - High-resolution 2D architectural CAD cross-section (ShelterVisualizer)
 * - 24-Hour Diurnal Operative Temperature Recharts graph (outdoor vs baseline vs optimized vs IMAC)
 * - Calculated 24-hour Indoor Operative Temperature telemetry data schedule
 * - Envelope Bill of Materials & Thermodynamic Properties table (NBC 2016 / SP 41)
 * - Formal engineering report header ("SIH26051: Area-Specific Shelter Thermal Report", location parameters, "Generated by: Team CODE TITANS")
 * - Formal engineering footer with NBC 2016 & IMAC-NV compliance certification
 */

import React, { useState, useMemo, useRef } from 'react';
import { ClimateData, ShelterDesign, SimulationResults } from '../types';
import { ShelterVisualizer } from './ShelterVisualizer';
import { getMaterialById } from '../data/materials';
import { calculateBillOfQuantities, calculateShapeGeometry } from '../services/costCalculator';
import { exportReportToPdf } from '../utils/pdfExport';
import { evaluateGovernmentCompliance } from '../services/complianceRules';
import { evaluateVulnerabilities } from '../services/vulnerabilityEngine';
import {
  Printer,
  Download,
  Loader2,
  ArrowLeft,
  ShieldCheck,
  Building2,
  Calendar,
  MapPin,
  Compass,
  CheckCircle2,
  AlertTriangle,
  FileCheck,
  ChevronDown,
  ChevronUp,
  Activity,
  Layers,
  Thermometer,
  Sun,
  Droplets,
  Wind
} from 'lucide-react';
import {
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine
} from 'recharts';

interface ReportViewProps {
  design: ShelterDesign;
  climate: ClimateData;
  results: SimulationResults;
  onBackToStudio: () => void;
}

export const ReportView: React.FC<ReportViewProps> = ({
  design,
  climate,
  results,
  onBackToStudio
}) => {
  const [showFull24HrTable, setShowFull24HrTable] = useState(false);

  const wallMat = getMaterialById(design.wallMaterialId);
  const roofMat = getMaterialById(design.roofMaterialId);
  const insMat = getMaterialById(design.insulationMaterialId);
  const glazeMat = getMaterialById(design.glazingMaterialId);

  // Mathematical shape metrics & itemized Bill of Quantities
  const shapeGeom = useMemo(() => calculateShapeGeometry(design.geometry), [design.geometry]);
  const boq = useMemo(() => calculateBillOfQuantities(
    design.geometry,
    wallMat,
    roofMat,
    insMat,
    glazeMat
  ), [design.geometry, wallMat, roofMat, insMat, glazeMat]);

  // Automated Rule-Based Vulnerability & Environmental Risk Assessment
  const vulnerabilityAssessment = useMemo(() => evaluateVulnerabilities(design, climate), [design, climate]);
  const complianceReport = useMemo(() => evaluateGovernmentCompliance(design, climate, results), [design, climate, results]);

  // Direct client-side PDF export ref & states
  const reportRef = useRef<HTMLDivElement>(null);
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [exportStatus, setExportStatus] = useState('');
  const [exportToast, setExportToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null);

  // Directly compile & download high-res multi-page A4 PDF file (bypasses iframe restrictions)
  const handleExportPdf = async () => {
    if (!reportRef.current || isExportingPdf) return;
    setIsExportingPdf(true);
    setExportStatus('Preparing report...');
    setExportToast(null);

    try {
      const sanitizedRoof = design.geometry.roofType.replace(/[^a-zA-Z0-9]/g, '_');
      const filename = `SIH26051_Shelter_Report_${design.regionId}_${sanitizedRoof}.pdf`;

      const res = await exportReportToPdf(reportRef.current, {
        filename,
        onProgress: (msg) => setExportStatus(msg)
      });

      if (res.success) {
        setExportToast({
          type: 'success',
          message: `Engineering Dossier downloaded successfully: ${filename}`
        });
        setTimeout(() => setExportToast(null), 5000);
      } else {
        setExportToast({
          type: 'error',
          message: res.error || 'Export failed. Please try Print Dossier.'
        });
      }
    } catch (err: any) {
      setExportToast({
        type: 'error',
        message: err?.message || 'Failed to generate PDF document.'
      });
    } finally {
      setIsExportingPdf(false);
      setExportStatus('');
    }
  };

  // Trigger browser's native print engine with automatic fallback
  const handlePrint = () => {
    try {
      window.print();
    } catch (err) {
      console.warn('Native window.print() was blocked or failed, falling back to direct PDF compilation:', err);
      handleExportPdf();
    }
  };

  // Prepare Recharts 24-hour diurnal thermal curve dataset
  const chartData = results.hourlyProfiles.map((p) => ({
    hour: `${p.hour.toString().padStart(2, '0')}:00`,
    'Outdoor Ambient': Number.isFinite(p.outdoorTempC) ? p.outdoorTempC : 25,
    'Baseline Design': Number.isFinite(p.indoorTempBaselineC) ? p.indoorTempBaselineC : 26,
    'Optimized Design': Number.isFinite(p.indoorTempOptimizedC) ? p.indoorTempOptimizedC : 24,
    'IMAC Neutral': Number.isFinite(p.imacNeutralTempC) ? p.imacNeutralTempC : 24.5,
    imacMin: Number.isFinite(p.imacLowerLimit80C) ? p.imacLowerLimit80C : 21.0,
    imacMax: Number.isFinite(p.imacUpperLimit80C) ? p.imacUpperLimit80C : 28.0
  }));

  // Min and max for chart Y domain
  const allTemps = results.hourlyProfiles
    .flatMap((p) => [
      p.outdoorTempC,
      p.indoorTempBaselineC,
      p.indoorTempOptimizedC,
      p.imacLowerLimit80C,
      p.imacUpperLimit80C
    ])
    .filter((n) => typeof n === 'number' && Number.isFinite(n));

  const validMin = allTemps.length > 0 ? Math.min(...allTemps) : 12;
  const validMax = allTemps.length > 0 ? Math.max(...allTemps) : 38;
  const yMin = Math.floor(validMin - 2);
  const yMax = Math.ceil(validMax + 2);

  const isComfortCompliant = results.percentComfortCompliance80 >= 75;

  const currentDateFormatted = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric'
  });

  const currentTimeFormatted = new Date().toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit'
  });

  return (
    <div className="space-y-6 max-w-5xl mx-auto print:max-w-none print:w-full print:m-0 print:p-0 print:space-y-4">
      {/* ========================================================================= */}
      {/* 1. TOP ACTION TOOLBAR (Strictly Hidden during Print via print:hidden)       */}
      {/* ========================================================================= */}
      <div className="no-print print:hidden flex flex-wrap items-center justify-between gap-3 bg-white p-4 border border-slate-200 rounded-xl shadow-sm">
        <button
          type="button"
          onClick={onBackToStudio}
          className="px-3.5 py-2 text-xs font-semibold text-slate-700 hover:text-slate-900 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-lg flex items-center gap-2 transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4 text-slate-500" />
          <span>Back to Design Studio</span>
        </button>

        {/* Export Notification Toast */}
        {exportToast && (
          <div
            className={`px-3 py-1.5 rounded-lg text-xs font-medium flex items-center gap-2 border transition-all ${
              exportToast.type === 'success'
                ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                : 'bg-red-50 text-red-800 border-red-200'
            }`}
          >
            {exportToast.type === 'success' ? (
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
            ) : (
              <AlertTriangle className="w-3.5 h-3.5 text-red-600 shrink-0" />
            )}
            <span>{exportToast.message}</span>
          </div>
        )}

        <div className="flex items-center gap-2.5">
          <div className="hidden lg:block text-right mr-1">
            <div className="text-xs font-bold text-slate-800">A4 Engineering Dossier</div>
            <div className="text-[10px] text-slate-500 font-mono">210 × 297 mm Multi-Page Ready</div>
          </div>

          {/* Primary Action: Direct Client-Side A4 PDF Download */}
          <button
            type="button"
            onClick={handleExportPdf}
            disabled={isExportingPdf}
            id="save-pdf-button"
            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 active:bg-emerald-800 disabled:bg-emerald-500 text-white rounded-lg text-xs font-bold flex items-center gap-2 shadow-sm hover:shadow transition-all cursor-pointer"
            title="Directly compile and download multi-page A4 PDF file (works in all browsers & iframes)"
          >
            {isExportingPdf ? (
              <Loader2 className="w-4 h-4 text-white animate-spin" />
            ) : (
              <Download className="w-4 h-4 text-white" />
            )}
            <span>{isExportingPdf ? (exportStatus || 'Compiling PDF...') : 'Save as PDF (.pdf)'}</span>
          </button>

          {/* Secondary Action: Browser Native Print Dialog */}
          <button
            type="button"
            onClick={handlePrint}
            id="print-report-button"
            className="px-4 py-2 bg-slate-900 hover:bg-slate-800 active:bg-slate-950 text-white rounded-lg text-xs font-bold flex items-center gap-2 shadow-sm hover:shadow transition-all cursor-pointer"
            title="Open standard browser print dialog"
          >
            <Printer className="w-4 h-4 text-white" />
            <span>Print Dossier</span>
          </button>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* 2. PRINTABLE A4 ENGINEERING DOSSIER CONTAINER                             */}
      {/* ========================================================================= */}
      <div
        id="printable-dossier"
        ref={reportRef}
        className="print-page bg-white border border-slate-200 rounded-xl p-6 sm:p-10 shadow-sm text-slate-900 space-y-6 print:border-none print:shadow-none print:p-0 print:m-0 print:space-y-4 font-sans"
      >
        
        {/* ======================================================================= */}
        {/* A. FORMAL ENGINEERING REPORT HEADER (Required in Prompt)                 */}
        {/* ======================================================================= */}
        <header className="report-header border-b-2 border-slate-900 pb-4 space-y-3 print:break-inside-avoid">
          {/* Top Identifier & Regulation Banner */}
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 pb-2">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 bg-blue-600 rounded-full" />
              <span className="text-[11px] font-mono font-bold tracking-wider text-slate-600 uppercase">
                SMART INDIA HACKATHON 2026 | PROBLEM CODE: SIH26051
              </span>
            </div>
            <div className="flex items-center gap-1.5 px-2.5 py-0.5 rounded bg-emerald-50 border border-emerald-300 text-emerald-800 font-mono text-[10px] font-bold">
              <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" />
              <span>NBC 2016 & IMAC-NV COMPLIANT DESIGN</span>
            </div>
          </div>

          {/* Main Title & Problem Definition */}
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div className="space-y-1">
              <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-950 font-serif">
                SIH26051: Area-Specific Shelter Thermal Report
              </h1>
              <p className="text-xs sm:text-sm text-slate-600 font-medium">
                Software Based Model Development for Design of Area-Specific Shelter for Thermal Comfort Maintenance
              </p>
            </div>

            <div className="text-left sm:text-right font-mono text-xs text-slate-700 bg-slate-50 print:bg-transparent p-2.5 sm:p-0 rounded border sm:border-0 border-slate-200 shrink-0">
              <div><strong className="text-slate-900">Generated by:</strong> Team CODE TITANS</div>
              <div><strong className="text-slate-900">Dossier Ref:</strong> {design.id.slice(0, 14)}</div>
              <div><strong className="text-slate-900">Issue Date:</strong> {currentDateFormatted} ({currentTimeFormatted})</div>
            </div>
          </div>

          {/* Selected Location & Environment Parameters Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 bg-slate-50 print:bg-slate-50/80 p-3 rounded-lg border border-slate-200 font-mono text-xs">
            <div>
              <div className="text-[10px] uppercase font-bold text-slate-500 flex items-center gap-1">
                <MapPin className="w-3 h-3 text-blue-600" />
                Site Location
              </div>
              <div className="font-bold text-slate-900 text-xs mt-0.5 truncate">
                {climate.locationName}
              </div>
              <div className="text-[10px] text-slate-500">
                {climate.latitude.toFixed(2)}°N, {climate.longitude.toFixed(2)}°E • {climate.elevationMeters}m MSL
              </div>
            </div>

            <div>
              <div className="text-[10px] uppercase font-bold text-slate-500 flex items-center gap-1">
                <Compass className="w-3 h-3 text-amber-600" />
                Climatic Zone
              </div>
              <div className="font-bold text-slate-900 text-xs mt-0.5 uppercase">
                {climate.regionName}
              </div>
              <div className="text-[10px] text-slate-500 capitalize">
                Zone: {climate.climateZone.replace('_', ' ')}
              </div>
            </div>

            <div>
              <div className="text-[10px] uppercase font-bold text-slate-500 flex items-center gap-1">
                <Thermometer className="w-3 h-3 text-red-500" />
                Outdoor Ambient Range
              </div>
              <div className="font-bold text-slate-900 text-xs mt-0.5">
                {climate.minTempC}°C to {climate.maxTempC}°C
              </div>
              <div className="text-[10px] text-slate-500">
                Mean: {climate.outdoorTempC}°C • ΔT Swing: {climate.diurnalSwingC}°C
              </div>
            </div>

            <div>
              <div className="text-[10px] uppercase font-bold text-slate-500 flex items-center gap-1">
                <Sun className="w-3 h-3 text-amber-500" />
                Solar & Wind
              </div>
              <div className="font-bold text-slate-900 text-xs mt-0.5">
                {climate.directNormalSolarRadiationWm2} W/m² Peak
              </div>
              <div className="text-[10px] text-slate-500">
                RH: {climate.relativeHumidityPercent}% • Wind: {climate.windSpeedMs} m/s
              </div>
            </div>
          </div>
        </header>

        {/* ======================================================================= */}
        {/* B. EXECUTIVE SUMMARY: KEY THERMODYNAMIC & COMPLIANCE PERFORMANCE        */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid space-y-2">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 font-mono text-xs">
            {/* KPI 1: IMAC 80% Compliance */}
            <div className="p-3.5 rounded-lg border border-slate-200 bg-slate-50/70 print:bg-white print:border-slate-300">
              <div className="text-slate-500 text-[10px] uppercase font-bold tracking-wider">
                IMAC 80% COMPLIANCE
              </div>
              <div className={`text-xl font-bold mt-1 ${isComfortCompliant ? 'text-emerald-700' : 'text-amber-700'}`}>
                {results.percentComfortCompliance80}%
              </div>
              <div className="text-[11px] text-slate-600 mt-0.5">
                {results.hoursInComfortBand80} of 24 diurnal hours
              </div>
              <div className="text-[10px] text-slate-500 mt-1">
                Band: {results.imacComfortBand80.min}°C – {results.imacComfortBand80.max}°C
              </div>
            </div>

            {/* KPI 2: Thermal Mass Damping */}
            <div className="p-3.5 rounded-lg border border-slate-200 bg-slate-50/70 print:bg-white print:border-slate-300">
              <div className="text-slate-500 text-[10px] uppercase font-bold tracking-wider">
                THERMAL DAMPING & LAG
              </div>
              <div className="text-xl font-bold text-slate-900 mt-1">
                {results.diurnalDampingPercent}% Attenuation
              </div>
              <div className="text-[11px] text-slate-600 mt-0.5">
                {results.thermalLagHours} Hours Thermal Phase Shift
              </div>
              <div className="text-[10px] text-slate-500 mt-1">
                Delay time to indoor peak
              </div>
            </div>

            {/* KPI 3: Operative Temperature Range */}
            <div className="p-3.5 rounded-lg border border-slate-200 bg-slate-50/70 print:bg-white print:border-slate-300">
              <div className="text-slate-500 text-[10px] uppercase font-bold tracking-wider">
                OPERATIVE TEMP RANGE
              </div>
              <div className="text-xl font-bold text-slate-900 mt-1">
                {results.minIndoorTempC}°C – {results.peakIndoorTempC}°C
              </div>
              <div className="text-[11px] text-slate-600 mt-0.5">
                Indoor swing: Δ{(Number(results.peakIndoorTempC) - Number(results.minIndoorTempC)).toFixed(1)}°C
              </div>
              <div className="text-[10px] text-slate-500 mt-1">
                Outdoor swing: Δ{climate.diurnalSwingC}°C
              </div>
            </div>

            {/* KPI 4: Bill of Materials Cost & Carbon */}
            <div className="p-3.5 rounded-lg border border-slate-200 bg-slate-50/70 print:bg-white print:border-slate-300">
              <div className="text-slate-500 text-[10px] uppercase font-bold tracking-wider">
                ESTIMATED CAPITAL COST
              </div>
              <div className="text-xl font-bold text-slate-900 mt-1">
                ₹{results.estimatedMaterialCostINR.toLocaleString('en-IN')}
              </div>
              <div className="text-[11px] text-slate-600 mt-0.5">
                Embodied: {results.embodiedCarbonTotalKg} kg CO₂e
              </div>
              <div className="text-[10px] text-slate-500 mt-1">
                Carbon Intensity: {((results.embodiedCarbonTotalKg || 0) / Math.max(1, (design.geometry.lengthMeters || 6) * (design.geometry.widthMeters || 4.5))).toFixed(1)} kg/m²
              </div>
            </div>
          </div>
        </section>

        {/* ======================================================================= */}
        {/* C. SECTION 1: 2D ARCHITECTURAL CROSS-SECTION & FLUX MODEL (CAD)         */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid space-y-2">
          <div className="flex items-center justify-between border-b border-slate-200 pb-1.5">
            <h2 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-slate-900 flex items-center gap-2">
              <Building2 className="w-4 h-4 text-blue-600" />
              <span>1. Parametric 2D Architectural Cross-Section & Thermal Flux Vector Model</span>
            </h2>
            <span className="text-[11px] font-mono text-slate-500">NBC 2016 Scale 1:50</span>
          </div>

          <div className="rounded-lg border border-slate-300 overflow-hidden bg-slate-950 print:border-slate-400">
            <ShelterVisualizer
              design={design}
              climate={climate}
              results={results}
              readOnlyControls={true}
            />
          </div>

          <div className="flex flex-wrap items-center justify-between text-[10px] font-mono text-slate-500 px-1">
            <span>Geometry: {design.geometry.lengthMeters}m (L) × {design.geometry.widthMeters}m (W) × {design.geometry.heightMeters}m (H) • WWR: {design.geometry.windowToWallRatioPercent}%</span>
            <span>Roof: {design.geometry.roofType} ({design.geometry.roofPitchDegrees}°) • Overhang: {design.geometry.overhangDepthMeters}m Chhajja</span>
          </div>
        </section>

        {/* ======================================================================= */}
        {/* D. SECTION 2: 24-HOUR DIURNAL OPERATIVE TEMPERATURE RECHARTS GRAPH     */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid space-y-2">
          <div className="flex flex-wrap items-center justify-between border-b border-slate-200 pb-1.5 gap-2">
            <h2 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-slate-900 flex items-center gap-2">
              <Activity className="w-4 h-4 text-blue-600" />
              <span>2. 24-Hour Diurnal Thermal Performance vs. NBC 2016 IMAC Adaptive Comfort Band</span>
            </h2>
            <span className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold border ${
              isComfortCompliant
                ? 'bg-emerald-50 text-emerald-800 border-emerald-300'
                : 'bg-amber-50 text-amber-800 border-amber-300'
            }`}>
              Compliance: {results.percentComfortCompliance80}% (80% Acceptability)
            </span>
          </div>

          {/* Clean Recharts Line Graph formatted for print */}
          <div className="p-3 bg-white border border-slate-200 rounded-lg print:border-slate-300">
            <div className="w-full h-64 sm:h-72 print:h-64">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData} margin={{ top: 12, right: 24, left: -10, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis
                    dataKey="hour"
                    stroke="#475569"
                    fontSize={10}
                    interval={2}
                    tickLine={false}
                  />
                  <YAxis
                    stroke="#475569"
                    fontSize={10}
                    domain={[yMin, yMax]}
                    unit="°C"
                    tickLine={false}
                  />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#0f172a',
                      borderColor: '#334155',
                      borderRadius: '6px',
                      color: '#f8fafc',
                      fontSize: '11px',
                      fontFamily: 'monospace'
                    }}
                    formatter={(val: any) => [`${val}°C`]}
                  />
                  <Legend
                    wrapperStyle={{ fontSize: '10px', fontFamily: 'monospace', paddingTop: '6px' }}
                    iconType="plainline"
                  />

                  {/* IMAC 80% Comfort Band Boundaries */}
                  <ReferenceLine
                    y={results.imacComfortBand80.max}
                    stroke="#059669"
                    strokeDasharray="4 4"
                    strokeWidth={1.5}
                    label={{
                      value: `IMAC Upper Limit (${results.imacComfortBand80.max}°C)`,
                      position: 'insideTopRight',
                      fill: '#059669',
                      fontSize: 9,
                      fontFamily: 'monospace'
                    }}
                  />
                  <ReferenceLine
                    y={results.imacComfortBand80.min}
                    stroke="#059669"
                    strokeDasharray="4 4"
                    strokeWidth={1.5}
                    label={{
                      value: `IMAC Lower Limit (${results.imacComfortBand80.min}°C)`,
                      position: 'insideBottomRight',
                      fill: '#059669',
                      fontSize: 9,
                      fontFamily: 'monospace'
                    }}
                  />

                  {/* Outdoor Ambient curve */}
                  <Line
                    type="monotone"
                    dataKey="Outdoor Ambient"
                    stroke="#ef4444"
                    strokeWidth={1.8}
                    dot={false}
                    name="Outdoor Ambient (To)"
                  />

                  {/* Baseline Shelter curve */}
                  <Line
                    type="monotone"
                    dataKey="Baseline Design"
                    stroke="#94a3b8"
                    strokeDasharray="4 4"
                    strokeWidth={1.5}
                    dot={false}
                    name="Standard Baseline (Tbase)"
                  />

                  {/* Optimized Shelter Operative Temperature */}
                  <Line
                    type="monotone"
                    dataKey="Optimized Design"
                    stroke="#2563eb"
                    strokeWidth={2.4}
                    dot={{ r: 2, fill: '#2563eb' }}
                    name="Optimized Shelter Operative Temp (Top)"
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <div className="mt-2 text-[10px] font-mono text-slate-500 flex flex-wrap justify-between border-t border-slate-100 pt-1.5">
              <span>Outdoor Peak: {climate.maxTempC}°C at 14:00 • Indoor Operative Peak: {results.peakIndoorTempC}°C at {14 + results.thermalLagHours >= 24 ? (14 + results.thermalLagHours - 24) : (14 + results.thermalLagHours)}:00</span>
              <span>Thermal Phase Shift Delay: {results.thermalLagHours} Hours • Amplitude Reduction: {results.diurnalDampingPercent}%</span>
            </div>
          </div>
        </section>

        {/* ======================================================================= */}
        {/* E. SECTION 3: CALCULATED INDOOR OPERATIVE TEMPERATURE DATA SCHEDULE     */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid space-y-2">
          <div className="flex items-center justify-between border-b border-slate-200 pb-1.5">
            <h2 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-slate-900 flex items-center gap-2">
              <Layers className="w-4 h-4 text-blue-600" />
              <span>3. Calculated Diurnal Indoor Operative Temperature Data Schedule</span>
            </h2>

            {/* Screen toggle to expand all 24 rows if desired, prints 24 rows cleanly */}
            <button
              type="button"
              onClick={() => setShowFull24HrTable(!showFull24HrTable)}
              className="no-print print:hidden text-[11px] font-mono text-blue-600 hover:text-blue-800 flex items-center gap-1 cursor-pointer"
            >
              <span>{showFull24HrTable ? 'Show Key Hourly Sample (8 Rows)' : 'Show Full 24-Hour Table'}</span>
              {showFull24HrTable ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            </button>
          </div>

          <div className="overflow-x-auto border border-slate-200 rounded-lg print:border-slate-300">
            <table className="w-full text-left text-xs border-collapse font-mono">
              <thead className="bg-slate-100 text-slate-700 text-[10px] uppercase font-bold border-b border-slate-200">
                <tr>
                  <th className="p-2 border-r border-slate-200">Hour</th>
                  <th className="p-2 border-r border-slate-200 text-right">Outdoor (To)</th>
                  <th className="p-2 border-r border-slate-200 text-right">Baseline (Tbase)</th>
                  <th className="p-2 border-r border-slate-200 text-right font-bold text-slate-900">Operative (Top)</th>
                  <th className="p-2 border-r border-slate-200 text-right">Damping (ΔT)</th>
                  <th className="p-2 border-r border-slate-200 text-right">Solar (W/m²)</th>
                  <th className="p-2 text-center">IMAC 80% Band</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 text-[11px]">
                {results.hourlyProfiles
                  .filter((p) => {
                    // In print mode, always show all 24 rows; on screen, toggle between key hours and all 24
                    if (showFull24HrTable) return true;
                    return [0, 3, 6, 9, 12, 14, 18, 21].includes(p.hour);
                  })
                  .map((p) => {
                    const solar = climate.hourlySolarRadiationWm2[p.hour] || 0;
                    const deltaT = (p.outdoorTempC - p.indoorTempOptimizedC).toFixed(1);
                    const isWithinBand =
                      p.indoorTempOptimizedC >= p.imacLowerLimit80C &&
                      p.indoorTempOptimizedC <= p.imacUpperLimit80C;
                    const isHot = p.indoorTempOptimizedC > p.imacUpperLimit80C;

                    return (
                      <tr
                        key={p.hour}
                        className={p.hour === 14 ? 'bg-amber-50/60 font-semibold' : 'hover:bg-slate-50'}
                      >
                        <td className="p-2 border-r border-slate-200 font-bold">
                          {p.hour.toString().padStart(2, '0')}:00 {p.hour === 14 ? '(Solar Peak)' : ''}
                        </td>
                        <td className="p-2 border-r border-slate-200 text-right text-red-700">
                          {p.outdoorTempC.toFixed(1)}°C
                        </td>
                        <td className="p-2 border-r border-slate-200 text-right text-slate-600">
                          {p.indoorTempBaselineC.toFixed(1)}°C
                        </td>
                        <td className="p-2 border-r border-slate-200 text-right font-bold text-blue-700">
                          {p.indoorTempOptimizedC.toFixed(1)}°C
                        </td>
                        <td className="p-2 border-r border-slate-200 text-right text-emerald-700">
                          {Number(deltaT) > 0 ? `-${deltaT}` : `+${Math.abs(Number(deltaT))}`}°C
                        </td>
                        <td className="p-2 border-r border-slate-200 text-right text-amber-700">
                          {solar}
                        </td>
                        <td className="p-2 text-center">
                          {isWithinBand ? (
                            <span className="inline-flex items-center gap-1 text-emerald-700 font-bold text-[10px]">
                              <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                              Comfortable
                            </span>
                          ) : isHot ? (
                            <span className="inline-flex items-center gap-1 text-red-700 font-bold text-[10px]">
                              <AlertTriangle className="w-3 h-3 text-red-500" />
                              Warm Excursion
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 text-sky-700 font-bold text-[10px]">
                              Cool Excursion
                            </span>
                          )}
                        </td>
                      </tr>
                    );
                  })}
              </tbody>
            </table>
          </div>
          <div className="text-[10px] font-mono text-slate-500 px-1">
            *Operative temperature (Top) evaluated combining mean radiant temperature (Tr) and indoor convective dry-bulb air temperature (Ta) per ASHRAE 55 and NBC 2016 Part 8.
          </div>
        </section>

        {/* ======================================================================= */}
        {/* F. SECTION 4: ARCHITECTURAL GEOMETRY & ITEMIZED BILL OF QUANTITIES (BOQ) */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid space-y-3">
          <div className="flex items-center justify-between border-b border-slate-200 pb-1.5">
            <h2 className="text-xs sm:text-sm font-bold uppercase tracking-wider text-slate-900 flex items-center gap-2">
              <FileCheck className="w-4 h-4 text-blue-600" />
              <span>4. Architectural Geometry & Itemized Bill of Quantities (BOQ) with Embodied Carbon</span>
            </h2>
            <span className="text-[11px] font-mono text-slate-500">CPWD / NBC 2016 Rates</span>
          </div>

          {/* 4.1 Shape Geometric Solver Summary */}
          <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-2 bg-slate-50 print:bg-slate-50/70 p-2.5 rounded-lg border border-slate-200 font-mono text-xs">
            <div>
              <div className="text-[10px] text-slate-500 uppercase">Base Form</div>
              <div className="font-bold text-slate-900 capitalize text-xs mt-0.5">{shapeGeom.shape.replace(/_/g, ' ')}</div>
            </div>
            <div>
              <div className="text-[10px] text-slate-500 uppercase">Floor Area</div>
              <div className="font-bold text-slate-900 text-xs mt-0.5">{shapeGeom.floorAreaM2} m²</div>
            </div>
            <div>
              <div className="text-[10px] text-slate-500 uppercase">Net Wall Area</div>
              <div className="font-bold text-slate-900 text-xs mt-0.5">{shapeGeom.netWallAreaM2} m²</div>
            </div>
            <div>
              <div className="text-[10px] text-slate-500 uppercase">Roof Area</div>
              <div className="font-bold text-slate-900 text-xs mt-0.5">{shapeGeom.roofAreaM2} m²</div>
            </div>
            <div>
              <div className="text-[10px] text-slate-500 uppercase">Internal Volume</div>
              <div className="font-bold text-slate-900 text-xs mt-0.5">{shapeGeom.internalVolumeM3} m³</div>
            </div>
            <div>
              <div className="text-[10px] text-slate-500 uppercase">S/V Ratio</div>
              <div className="font-bold text-sky-700 text-xs mt-0.5">{shapeGeom.surfaceAreaToVolumeRatio} m⁻¹</div>
            </div>
          </div>

          {/* 4.2 Itemized BOQ Table */}
          <div className="overflow-x-auto border border-slate-200 rounded-lg print:border-slate-300">
            <table className="w-full text-left text-xs border-collapse font-mono">
              <thead className="bg-slate-100 text-slate-700 text-[10px] uppercase font-bold border-b border-slate-200">
                <tr>
                  <th className="p-2 border-r border-slate-200">Item Description</th>
                  <th className="p-2 border-r border-slate-200 text-center">Unit</th>
                  <th className="p-2 border-r border-slate-200 text-right">Quantity</th>
                  <th className="p-2 border-r border-slate-200 text-right">Rate (₹)</th>
                  <th className="p-2 border-r border-slate-200 text-right font-bold text-slate-900">Amount (₹)</th>
                  <th className="p-2 text-right">Embodied CO₂ (kg)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 text-[11px]">
                {boq.items.map((it) => (
                  <tr key={it.id} className="hover:bg-slate-50">
                    <td className="p-2 border-r border-slate-200 font-medium">
                      {it.description}
                    </td>
                    <td className="p-2 border-r border-slate-200 text-center text-slate-500">
                      {it.unit}
                    </td>
                    <td className="p-2 border-r border-slate-200 text-right">
                      {it.quantity.toFixed(1)}
                    </td>
                    <td className="p-2 border-r border-slate-200 text-right text-slate-600">
                      ₹{it.rateINR.toLocaleString('en-IN')}
                    </td>
                    <td className="p-2 border-r border-slate-200 text-right font-bold text-slate-900">
                      ₹{it.amountINR.toLocaleString('en-IN')}
                    </td>
                    <td className="p-2 text-right text-emerald-800 font-medium">
                      {it.totalCarbonKg.toLocaleString('en-IN')} kg
                    </td>
                  </tr>
                ))}
                {/* BOQ Summary Totals Row */}
                <tr className="bg-slate-100/90 font-bold border-t-2 border-slate-300 text-xs">
                  <td colSpan={4} className="p-2.5 border-r border-slate-200 text-right uppercase tracking-wider text-slate-800">
                    Total Estimated Capital Cost & Embodied Carbon:
                  </td>
                  <td className="p-2.5 border-r border-slate-200 text-right text-blue-900 font-bold text-sm">
                    ₹{boq.totalCostINR.toLocaleString('en-IN')}
                  </td>
                  <td className="p-2.5 text-right text-emerald-900 font-bold text-sm">
                    {boq.totalEmbodiedCarbonKg.toLocaleString('en-IN')} kg CO₂e
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2 text-[10px] font-mono text-slate-500 px-1">
            <div>
              *Cost Index: ₹{boq.costPerFloorAreaINR.toLocaleString('en-IN')}/m² floor area • Carbon Intensity: {boq.carbonPerFloorAreaKg} kg CO₂e/m²
            </div>
            <div>
              *Wall U-Value: {results.compositeWallUValue} W/m²·K • Roof U-Value: {results.compositeRoofUValue} W/m²·K (IS 3792 / ECBC)
            </div>
          </div>
        </section>

        {/* ======================================================================= */}
        {/* G. SECTION 5: REGULATORY COMPLIANCE & IMAC ADAPTIVE COMFORT STATEMENT    */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid p-4 bg-slate-50 print:bg-slate-50/60 border border-slate-200 rounded-lg space-y-2 text-xs">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-blue-600" />
            <span>5. Regulatory Compliance & IMAC-NV Adaptive Comfort Certification</span>
          </h2>
          <p className="text-slate-700 leading-relaxed font-sans text-xs">
            Evaluated in accordance with the <strong>National Building Code of India (NBC 2016 Part 8)</strong>,
            the <strong>Eco-Niwas Samhita (ENS 2018)</strong>, and the <strong>CEPT University Indian Model for Adaptive Comfort (IMAC-NV)</strong> for
            naturally ventilated enclosures. Given a 30-day running mean outdoor ambient temperature
            (T_om) of <strong>{climate.runningMeanOutdoorTempC}°C</strong>, the neutral operative comfort temperature is determined as:
            <span className="font-mono font-bold text-slate-900 ml-1">
              T_neutral = 0.54 × {climate.runningMeanOutdoorTempC} + 12.83 = {results.imacComfortNeutralTempC}°C
            </span>.
          </p>
          <p className="text-slate-700 leading-relaxed font-sans text-xs">
            The 80% occupant acceptability comfort corridor spans <strong>{results.imacComfortBand80.min}°C to {results.imacComfortBand80.max}°C</strong>.
            The engineered shelter successfully maintains indoor operative temperatures within this threshold for
            <strong className="text-emerald-800"> {results.hoursInComfortBand80} out of 24 diurnal hours ({results.percentComfortCompliance80}% thermal comfort compliance)</strong> without
            the use of active energy-intensive mechanical air conditioning.
          </p>
        </section>

        {/* ======================================================================= */}
        {/* G1. SECTION 5.1: STATUTORY INDIAN GOVERNMENT STANDARDS AUDIT (ECBC/NDMA/IMAC) */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid space-y-2.5 text-xs">
          <div className="border-b border-slate-200 pb-1 flex items-center justify-between">
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 flex items-center gap-1.5">
              <ShieldCheck className="w-3.5 h-3.5 text-blue-600" />
              <span>5.1 Indian Government Standards Compliance Audit (ECBC • NDMA • IMAC • NBC)</span>
            </h2>
            <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded ${
              complianceReport.isFullyCompliant
                ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                : 'bg-red-100 text-red-800 border border-red-300'
            }`}>
              {complianceReport.isFullyCompliant ? '100% CODE COMPLIANT' : `${complianceReport.violationCount} VIOLATIONS`}
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {complianceReport.items.map((item) => {
              const isViolated = item.severity === 'violation';
              const isDeviation = item.severity === 'deviation';
              const isPassed = item.severity === 'compliant';

              return (
                <div
                  key={item.id}
                  className={`p-2.5 rounded border text-[11px] space-y-1 ${
                    isViolated
                      ? 'bg-red-50/70 border-red-300 text-red-950'
                      : isDeviation
                      ? 'bg-amber-50/70 border-amber-300 text-amber-950'
                      : 'bg-emerald-50/70 border-emerald-300 text-emerald-950'
                  }`}
                >
                  <div className="flex items-center justify-between gap-1 font-mono text-[10px]">
                    <span className="font-bold flex items-center gap-1">
                      <span className={`w-2 h-2 rounded-full ${isViolated ? 'bg-red-600' : isDeviation ? 'bg-amber-500' : 'bg-emerald-600'}`} />
                      {item.authority} • {item.code}
                    </span>
                    <span className={`font-bold px-1.5 py-0.2 rounded uppercase text-[9px] ${
                      isViolated ? 'bg-red-200 text-red-900' : isDeviation ? 'bg-amber-200 text-amber-900' : 'bg-emerald-200 text-emerald-900'
                    }`}>
                      {item.severity}
                    </span>
                  </div>
                  <div className="font-bold text-xs">
                    {item.title}
                  </div>
                  <div className="text-[10px] text-slate-600 leading-tight">
                    {item.message}
                  </div>
                  <div className="text-[9px] font-mono text-slate-500 pt-0.5 border-t border-slate-200/60 flex justify-between">
                    <span>Limit: {item.legalLimit}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* ======================================================================= */}
        {/* H. SECTION 6: ARCHITECTURAL FINDINGS & CLIMATE-SPECIFIC OBSERVATIONS   */}
        {/* ======================================================================= */}
        <section className="print:break-inside-avoid space-y-2 text-xs">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <FileCheck className="w-3.5 h-3.5 text-blue-600" />
            <span>6. Architectural Findings & Area-Specific Recommendations</span>
          </h2>
          <ul className="list-disc pl-5 space-y-1.5 text-slate-700 font-sans text-xs">
            {results.engineeringObservations.map((obs, i) => (
              <li key={i} className="leading-normal">
                {obs}
              </li>
            ))}
          </ul>
        </section>

        {/* ======================================================================= */}
        {/* I. FORMAL ENGINEERING REPORT FOOTER (Required in Prompt)                 */}
        {/* ======================================================================= */}
        <footer className="report-footer pt-4 border-t-2 border-slate-900 flex flex-wrap items-center justify-between gap-3 text-[10px] text-slate-500 font-mono print:break-inside-avoid">
          <div>
            <div className="font-bold text-slate-800">
              SIH26051: Area-Specific Shelter Thermal Report • Generated by: Team CODE TITANS
            </div>
            <div className="text-slate-500">
              Smart India Hackathon 2026 • Area-Specific Shelter for Thermal Comfort Maintenance
            </div>
          </div>

          <div className="text-right">
            <div>Standards: NBC 2016 Part 8 • ECBC-R 2018 • IMAC-NV (CEPT)</div>
            <div className="text-emerald-700 font-bold">[ Verified Simulation Dossier • Ready for Field Fabrication ]</div>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default ReportView;
